### ISSUE TITLE
logo.svg is not deployed to site

### ISSUE THREAD

**Issue by iam-TJ** [cobalt-org/cobalt-org.github.io#14] opened 2017-09-30 08:01 UTC
Did no-one check the deployed site? The logo is missing. Doesn't look like this is related to issue #2 either.

```
$ wget --server-response -O /dev/null http://cobalt-org.github.io/public/images/logo.svg
--2017-09-30 08:58:58--  http://cobalt-org.github.io/public/images/logo.svg
Resolving cobalt-org.github.io (cobalt-org.github.io)... 151.101.17.147, 2a04:4e42:4::403
Connecting to cobalt-org.github.io (cobalt-org.github.io)|151.101.17.147|:80... connected.
HTTP request sent, awaiting response... 
  HTTP/1.1 404 Not Found
  Server: GitHub.com
  Content-Type: text/html; charset=utf-8
  ETag: "585337e5-247c"
  Access-Control-Allow-Origin: *
  Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; img-src data:; connect-src 'self'
  X-GitHub-Request-Id: 1ABA:14C0:1BD2A88:277AEDF:59CF4EC2
  Content-Length: 9340
  Accept-Ranges: bytes
  Date: Sat, 30 Sep 2017 07:58:58 GMT
  Via: 1.1 varnish
  Age: 0
  Connection: keep-alive
  X-Served-By: cache-lcy1148-LCY
  X-Cache: MISS
  X-Cache-Hits: 0
  X-Timer: S1506758339.851136,VS0,VE84
  Vary: Accept-Encoding
  X-Fastly-Request-ID: e9af20c1e341fb41ce8069bd3135ac35fb72d6de
2017-09-30 08:58:58 ERROR 404: Not Found.

```

**Comment by epage** [comment] 2017-09-30 15:17
Thanks for reminding me that I need to get this fixed.

The original problem is that cobalt was released with a bug that did not properly handle assets (cobalt-org/cobalt.rs#183).  Once that got fixed and cobalt was published, the problem is now that the credentials need to be updated.  I was hoping the current person's credentials would go and update them but I guess I'll switch it to my own credentials.

Note: this is being tracked in #10.  A lot more isn't working than just the logo.  Closing this as a duplicate.

**Closed by epage** 2017-09-30 15:17 UTC
